### ISSUE TITLE
Maven's Kodi-Builds Netflix Add-on related errors

### ISSUE THREAD

**Issue by Liqianyu** [Paco8/kodi-repo#5]
If you use Maven's Kodi Builds, after installing Netflix Mod Add-on, when you start Netflix, it will prompt "An upgrade of add-on service is in progress, please wait."
I tried skipping check_service_upgrade and was able to bypass this issue.

There seems to be an additional error on Maven's Kodi 21 (I'm not sure if it's on Kodi 20), where the first time you start the Netflix add-on it says "AttributeError: 'NoneType' object has no attribute 'split'".
Loading the Netflix add-on a second time gets you in, and it seems that if you first create the database using the Netflix add-on, you don't encounter this problem. Skipping G.IS_ADDON_FIRSTRUN bypasses this issue.

**Comment by Paco8** [comment]
I think the error "AttributeError: 'NoneType' object has no attribute 'split'" is fixed in mod2.

**Comment by Paco8** [comment]
I don't know, I never experienced that problem.
